"""
Localisation dictionary for the Go Vocal competitor-battlecard skill.

Scripts look up labels by key. Extend this dictionary when a new language is needed.
The keys are stable identifiers; never translate keys, only values.
"""

LABELS = {
    "en": {
        # Concept note
        "cover_label_connector": "  ×  ",
        "why_this_note": "Why this note",
        "go_vocal_in_numbers": "Go Vocal in numbers",
        "where_we_stand_out": "Where Go Vocal stands out",
        "the_opportunity": "The opportunity",
        "what_we_offer": "What we offer",
        "the_bottom_line": "The bottom line",
        "csat": "Customer Satisfaction Score",
        "countries": "Countries we work in",
        "governments": "Governments we have worked with",
        "people_powered": "People Powered score",
        "projects": "Projects launched",
        "monthly_admins": "Monthly active admins",
        # Spreadsheet
        "sheet_title": "Go Vocal × {competitor} — Feature Comparison",
        "sheet_subtitle": "A structured comparison across every product module — for {competitor} clients evaluating a migration to Go Vocal.",
        "col_num": "#",
        "col_requirement": "Requirement",
        "col_gv": "GV",
        "col_gv_detail": "Go Vocal — Details",
        "col_comp_detail_fmt": "{competitor} — Details",
        "legend_title": "Legend",
        "legend_green": "Fully supported natively, production-grade.",
        "legend_yellow": "Partially supported or on the near-term roadmap (specified inline).",
        "legend_red": "Not supported today; typically requires external tools or custom work.",
        "how_to_read": "How to read this document",
        "honesty_note_fmt": "Written honestly: where {competitor} does something Go Vocal doesn't yet, we say so.",
        "tab_overview": "Overview",
        "tab_1": "1. Engagement Methods",
        "tab_2": "2. Back-Office & Workflows",
        "tab_3": "3. Analysis & Reporting",
        "tab_4": "4. UX & Frontend",
        "tab_5": "5. Technical & Infrastructure",
        "tab_6": "6. Support & Services",
        "tab_1_desc": "Ideation, surveys, participatory budgeting, voting, debate, petitions.",
        "tab_2_desc": "Project management, contribution management, users & access, communication.",
        "tab_3_desc": "AI analysis, dashboards, reporting.",
        "tab_4_desc": "Resident-facing experience, mobile, mapping, accessibility, visual design, CMS.",
        "tab_5_desc": "Hosting, security, APIs, open source / open data, maintenance.",
        "tab_6_desc": "Onboarding, training, support, community of practice.",
    },
    "fr": {
        "cover_label_connector": "   ×   ",
        "why_this_note": "Pourquoi cette note",
        "go_vocal_in_numbers": "Go Vocal en chiffres",
        "where_we_stand_out": "Là où Go Vocal fait la différence",
        "the_opportunity": "L'enjeu",
        "what_we_offer": "Ce que nous proposons",
        "the_bottom_line": "En résumé",
        "csat": "Score de satisfaction client",
        "countries": "Pays où nous intervenons",
        "governments": "Gouvernements accompagnés",
        "people_powered": "Score People Powered",
        "projects": "Projets lancés",
        "monthly_admins": "Admins actifs par mois",
        "sheet_title": "Go Vocal × {competitor} — Comparatif fonctionnel",
        "sheet_subtitle": "Comparaison structurée couvrant chaque module produit — pour les clients {competitor} qui évaluent une migration vers Go Vocal.",
        "col_num": "#",
        "col_requirement": "Exigence",
        "col_gv": "GV",
        "col_gv_detail": "Go Vocal — Détails",
        "col_comp_detail_fmt": "{competitor} — Détails",
        "legend_title": "Légende",
        "legend_green": "Entièrement pris en charge nativement, qualité production.",
        "legend_yellow": "Partiellement pris en charge ou inscrit à la roadmap court terme (précisé en ligne).",
        "legend_red": "Non pris en charge à ce jour ; nécessite généralement des outils externes ou du développement sur-mesure.",
        "how_to_read": "Comment lire ce document",
        "honesty_note_fmt": "Écrit en toute honnêteté : là où {competitor} fait quelque chose que Go Vocal ne fait pas encore, nous le disons.",
        "tab_overview": "Vue d'ensemble",
        "tab_1": "1. Méthodes de participation",
        "tab_2": "2. Back-office & Workflows",
        "tab_3": "3. Analyse & Reporting",
        "tab_4": "4. UX & Frontend",
        "tab_5": "5. Technique & Infrastructure",
        "tab_6": "6. Support & Services",
        "tab_1_desc": "Idéation, enquêtes, budget participatif, vote, débat, pétitions.",
        "tab_2_desc": "Gestion de projet, traitement des contributions, utilisateurs & accès, communication.",
        "tab_3_desc": "Analyse IA, tableaux de bord, rapports.",
        "tab_4_desc": "Expérience habitant, mobile, cartographie, accessibilité, design, CMS.",
        "tab_5_desc": "Hébergement, sécurité, API, open source / open data, maintenance.",
        "tab_6_desc": "Onboarding, formation, support, communauté de pratique.",
    },
    "nl": {
        "cover_label_connector": "   ×   ",
        "why_this_note": "Waarom deze notitie",
        "go_vocal_in_numbers": "Go Vocal in cijfers",
        "where_we_stand_out": "Waar Go Vocal het verschil maakt",
        "the_opportunity": "De uitdaging",
        "what_we_offer": "Wat wij bieden",
        "the_bottom_line": "In het kort",
        "csat": "Klanttevredenheidsscore",
        "countries": "Landen waar we actief zijn",
        "governments": "Overheden waarmee we werk(t)en",
        "people_powered": "People Powered-score",
        "projects": "Gelanceerde projecten",
        "monthly_admins": "Actieve admins per maand",
        "sheet_title": "Go Vocal × {competitor} — Feature-vergelijking",
        "sheet_subtitle": "Gestructureerde vergelijking over elke productmodule — voor klanten van {competitor} die een overstap naar Go Vocal overwegen.",
        "col_num": "#",
        "col_requirement": "Vereiste",
        "col_gv": "GV",
        "col_gv_detail": "Go Vocal — Details",
        "col_comp_detail_fmt": "{competitor} — Details",
        "legend_title": "Legenda",
        "legend_green": "Volledig native ondersteund, productieklaar.",
        "legend_yellow": "Deels ondersteund of op de korte-termijn roadmap (inline toegelicht).",
        "legend_red": "Niet ondersteund; vereist meestal externe tools of maatwerk.",
        "how_to_read": "Hoe je dit document leest",
        "honesty_note_fmt": "Eerlijk geschreven: waar {competitor} iets beter doet dan Go Vocal, zeggen we dat.",
        "tab_overview": "Overzicht",
        "tab_1": "1. Participatiemethoden",
        "tab_2": "2. Back-office & Workflows",
        "tab_3": "3. Analyse & Rapportage",
        "tab_4": "4. UX & Frontend",
        "tab_5": "5. Techniek & Infrastructuur",
        "tab_6": "6. Support & Diensten",
        "tab_1_desc": "Ideevorming, enquêtes, participatieve budgetten, stemmen, debat, petities.",
        "tab_2_desc": "Projectbeheer, bijdragenbeheer, gebruikers & toegang, communicatie.",
        "tab_3_desc": "AI-analyse, dashboards, rapportage.",
        "tab_4_desc": "Bewonerservaring, mobiel, kaarten, toegankelijkheid, ontwerp, CMS.",
        "tab_5_desc": "Hosting, beveiliging, API's, open source / open data, onderhoud.",
        "tab_6_desc": "Onboarding, opleiding, support, community of practice.",
    },
    "de": {
        "cover_label_connector": "   ×   ",
        "why_this_note": "Warum diese Notiz",
        "go_vocal_in_numbers": "Go Vocal in Zahlen",
        "where_we_stand_out": "Wo Go Vocal den Unterschied macht",
        "the_opportunity": "Die Herausforderung",
        "what_we_offer": "Was wir bieten",
        "the_bottom_line": "Fazit",
        "csat": "Kundenzufriedenheit",
        "countries": "Länder, in denen wir tätig sind",
        "governments": "Verwaltungen, mit denen wir gearbeitet haben",
        "people_powered": "People-Powered-Wertung",
        "projects": "Gestartete Projekte",
        "monthly_admins": "Aktive Admins pro Monat",
        "sheet_title": "Go Vocal × {competitor} — Funktionsvergleich",
        "sheet_subtitle": "Strukturierter Vergleich über alle Produktmodule — für {competitor}-Kunden, die einen Wechsel zu Go Vocal prüfen.",
        "col_num": "#",
        "col_requirement": "Anforderung",
        "col_gv": "GV",
        "col_gv_detail": "Go Vocal — Details",
        "col_comp_detail_fmt": "{competitor} — Details",
        "legend_title": "Legende",
        "legend_green": "Nativ vollständig unterstützt, produktionsreif.",
        "legend_yellow": "Teilweise unterstützt oder auf der kurzfristigen Roadmap (inline spezifiziert).",
        "legend_red": "Heute nicht unterstützt; benötigt typischerweise externe Tools oder Sonderentwicklung.",
        "how_to_read": "So lesen Sie dieses Dokument",
        "honesty_note_fmt": "Ehrlich geschrieben: wo {competitor} etwas besser macht, sagen wir das.",
        "tab_overview": "Übersicht",
        "tab_1": "1. Beteiligungsmethoden",
        "tab_2": "2. Back-Office & Workflows",
        "tab_3": "3. Analyse & Reporting",
        "tab_4": "4. UX & Frontend",
        "tab_5": "5. Technik & Infrastruktur",
        "tab_6": "6. Support & Services",
        "tab_1_desc": "Ideenfindung, Umfragen, Bürgerhaushalt, Abstimmung, Debatte, Petitionen.",
        "tab_2_desc": "Projektsteuerung, Beitragsbearbeitung, Nutzer & Zugriff, Kommunikation.",
        "tab_3_desc": "KI-Analyse, Dashboards, Reporting.",
        "tab_4_desc": "Bürger-Erlebnis, Mobile, Karten, Barrierefreiheit, Design, CMS.",
        "tab_5_desc": "Hosting, Sicherheit, APIs, Open Source / Open Data, Wartung.",
        "tab_6_desc": "Onboarding, Schulung, Support, Community of Practice.",
    },
    "es": {
        "cover_label_connector": "   ×   ",
        "why_this_note": "Por qué esta nota",
        "go_vocal_in_numbers": "Go Vocal en cifras",
        "where_we_stand_out": "Dónde destaca Go Vocal",
        "the_opportunity": "El reto",
        "what_we_offer": "Lo que ofrecemos",
        "the_bottom_line": "En resumen",
        "csat": "Puntuación de satisfacción del cliente",
        "countries": "Países en los que trabajamos",
        "governments": "Administraciones con las que hemos trabajado",
        "people_powered": "Puntuación People Powered",
        "projects": "Proyectos lanzados",
        "monthly_admins": "Admins activos al mes",
        "sheet_title": "Go Vocal × {competitor} — Comparativa funcional",
        "sheet_subtitle": "Comparación estructurada por cada módulo de producto — para clientes de {competitor} que evalúan una migración a Go Vocal.",
        "col_num": "#",
        "col_requirement": "Requisito",
        "col_gv": "GV",
        "col_gv_detail": "Go Vocal — Detalles",
        "col_comp_detail_fmt": "{competitor} — Detalles",
        "legend_title": "Leyenda",
        "legend_green": "Totalmente compatible de forma nativa, listo para producción.",
        "legend_yellow": "Parcialmente compatible o en la hoja de ruta cercana (especificado en línea).",
        "legend_red": "No compatible hoy; suele requerir herramientas externas o desarrollo a medida.",
        "how_to_read": "Cómo leer este documento",
        "honesty_note_fmt": "Escrito con honestidad: donde {competitor} hace algo mejor que Go Vocal, lo decimos.",
        "tab_overview": "Resumen",
        "tab_1": "1. Métodos de participación",
        "tab_2": "2. Back-office y flujos",
        "tab_3": "3. Análisis y reporting",
        "tab_4": "4. UX y Frontend",
        "tab_5": "5. Técnica e infraestructura",
        "tab_6": "6. Soporte y servicios",
        "tab_1_desc": "Ideación, encuestas, presupuestos participativos, votación, debate, peticiones.",
        "tab_2_desc": "Gestión de proyectos, gestión de contribuciones, usuarios y acceso, comunicación.",
        "tab_3_desc": "Análisis IA, paneles, reporting.",
        "tab_4_desc": "Experiencia del vecino, móvil, cartografía, accesibilidad, diseño, CMS.",
        "tab_5_desc": "Hosting, seguridad, APIs, open source / open data, mantenimiento.",
        "tab_6_desc": "Onboarding, formación, soporte, comunidad de práctica.",
    },
}


def L(language: str, key: str, **fmt) -> str:
    """Look up a localised label, with optional formatting kwargs."""
    lang = language if language in LABELS else "en"
    text = LABELS[lang].get(key)
    if text is None:
        text = LABELS["en"].get(key, key)
    if fmt:
        return text.format(**fmt)
    return text
